---
language: python
sudo: required
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
  matrix:
    - DB_PASSWD=travis_test_password
      SECRET_KEY='n85(tdv64&xx=$4s_e6^&$-icomxm75k(%443%55&-lfq_y=+k'
      PIPENV_VERBOSITY=-1
services:
  - postgresql
# command to install dependencies
install:
  - ./setup.sh
# command to run tests
script:
  - pipenv run python ./manage.py test
