# Generated by Django 2.1.2 on 2018-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('title', models.CharField(help_text='A section heading in a menu.', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='A longer description of the section, for e.g. a tooltip', max_length=255)),
            ],
        ),
    ]
