# Generated by Django 2.1.2 on 2018-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Category title', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='brief description', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProject',
            fields=[
                ('title', models.CharField(help_text='Common name of the software project.', max_length=50, primary_key=True, serialize=False)),
                ('github_repo', models.CharField(help_text='repo name in google (between "alflanagn/" and ".git" in URL)', max_length=50)),
                ('sync_github', models.BooleanField(default=True, help_text='Should this repo be automatically synchronized with Github?')),
                ('created_at', models.DateTimeField(help_text='Date repo first created or first document written', verbose_name='Date Created')),
                ('starred', models.BooleanField(default=False, help_text='Is the repo starred on github?')),
                ('blurb', models.TextField(help_text='Short description of the project, about a paragraph.')),
            ],
        ),
        migrations.CreateModel(
            name='TechUsed',
            fields=[
                ('name', models.CharField(help_text='Short name of technology', max_length=30, primary_key=True, serialize=False)),
                ('notes', models.TextField(help_text='Notes to describe technology, my history with it, my opinions, etc.')),
                ('stars', models.IntegerField(help_text='Totally subjective rating of the technology.')),
            ],
        ),
    ]
