# Generated by Django 2.1.2 on 2018-10-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20181025_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTechUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='The version(s) of the tech used.', max_length=40)),
                ('description', models.CharField(blank=True, help_text='brief description of why/how tech is being used', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'software techs used',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='techused',
            options={'verbose_name_plural': 'techs used'},
        ),
        migrations.RemoveField(
            model_name='softwareproject',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='brief description', max_length=250),
        ),
        migrations.AlterField(
            model_name='softwareproject',
            name='blurb',
            field=models.TextField(blank=True, help_text='Short description of the project, about a paragraph.'),
        ),
        migrations.AlterField(
            model_name='softwareproject',
            name='github_repo',
            field=models.CharField(blank=True, help_text='repo name in google (between "alflanagn/" and ".git" in URL)', max_length=50),
        ),
        migrations.AlterField(
            model_name='techused',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to describe technology, my history with it, my opinions, etc.'),
        ),
        migrations.AlterField(
            model_name='techused',
            name='stars',
            field=models.IntegerField(help_text='Totally subjective rating of the technology.', null=True),
        ),
        migrations.AddField(
            model_name='softwaretechused',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.SoftwareProject'),
        ),
        migrations.AddField(
            model_name='softwaretechused',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.TechUsed'),
        ),
        migrations.AlterUniqueTogether(
            name='softwaretechused',
            unique_together={('project', 'tech')},
        ),
    ]
