# Generated by Django 2.1.2 on 2018-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20181025_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechUsed',
            new_name='Technology',
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'technologies'},
        ),
    ]
